# ì„œë²„ ì„¤ì •
server:
  # ë°ì´í„°ì†ŒìŠ¤ ì„¤ì •
  datasource:
    url: jdbc:postgresql://my-postgres:5432/forjun
    username: forjun
    password: forjun406
    driver-class-name: org.postgresql.Driver

  # JPA ì„¤ì •
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# íŒŒì¼ ì—…ë¡œë“œ ì„¤ì •
file:
  upload-dir: uploads/images

# ì•”í˜¸í™” ì„¤ì •
encryption:
  secret-key: MySecretKey123456789012345678901234567890

# ë¡œê·¸ ì„¤ì •
logging:
  com.pos.commerce: INFO

  # Spring í”„ë ˆì„ì›Œí¬
  org.springframework.web: INFO
  org.springframework.security: INFO
  org.springframework.data.jpa: INFO
  org.springframework.transaction: INFO
  org.springframework.web.servlet: INFO

  # ğŸ’¡ SQL ë¡œê·¸
  org.hibernate.type.descriptor.sql.BasicBinder: WARN
  org.hibernate.SQL: WARN
