server:
  port: 8080
  tomcat:
    max-threads: 100
    max-connections: 1000
    min-spare-threads: 10
    max-http-post-size: 10MB
    max-http-put-size: 10MB
    max-http-delete-size: 10MB
    max-http-head-size: 10MB
    max-http-options-size: 10MB

spring:
  application:
    name: commerce

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  datasource:
    url: jdbc:postgresql://34.64.50.124:5432/forjun
    username: forjun
    password: forjun406
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

file:
  upload-dir: uploads/images

logging:
  level:
    com.pos.commerce: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.web.servlet: DEBUG
    org.springframework.web.filter: DEBUG
