server:
  port: 8081
  tomcat:
    max-threads: 100 # 최대 스레드 수
    max-connections: 1000 # 최대 연결 수
    min-spare-threads: 10 # 최소 스레드 수
    max-http-post-size: 50MB # 최대 POST 요청 크기
    max-http-put-size: 50MB # 최대 PUT 요청 크기
    max-http-delete-size: 1MB # 최대 DELETE 요청 크기
    max-http-head-size: 1MB # 최대 HEAD 요청 크기
    max-http-options-size: 1MB # 최대 OPTIONS 요청 크기

spring:
  application:
    name: pos-system

  servlet:
    multipart:
      max-file-size: 10MB # 최대 파일 크기
      max-request-size: 50MB # 최대 요청 크기
  profiles:
    active: ${spring.profiles.active:dev} # 프로파일 설정
